package com.watchwise.watchwise_api.diaryentry.dto;

import com.watchwise.watchwise_api.content.entity.ContentType;

import java.time.LocalDate;
import java.util.UUID;

public record DeletionImpactItemDTO(
        UUID id,
        ContentType type,
        LocalDate watchedDate,
        Integer watchNumber,
        boolean autoGenerated,
        boolean hasReview
) {
}
